export const TIME_CONSTANTS = {
  MILLISECONDS_PER_HOUR: 60 * 60 * 1000,
  RATE_LIMIT_WINDOW: 300000, // 5 minutes
} as const;

export const ANIMATION_CONSTANTS = {
  DEFAULT_SPEED: 1,
  DEFAULT_INTENSITY: 1,
  FLOAT_AMPLITUDE: 0.5,
  SCALE_MIN: 0.8,
  SCALE_MAX: 1.2,
  PULSE_MIN: 0.2,
  PULSE_MAX: 1.0,
  ORBIT_RADIUS: 2,
} as const;

export const ERROR_CONSTANTS = {
  MAX_QUEUE_SIZE: 50,
  MAX_REQUESTS_PER_HOUR: 100,
  RATE_LIMIT_THRESHOLD: 5,
} as const;