/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useState } from 'react'

import { Html } from '@react-three/drei'
import { GLTFLoader } from 'three-stdlib'

export default function Model() {
  /* State */
  const [model, setModel] = useState()

  /* Load model */
  useEffect(() => {
    const loader = new GLTFLoader()
    loader.load('room.gltf', async (gltf) => {
      const nodes = await gltf.parser.getDependencies('node')
      setModel(nodes[0])
    })
  }, [])

  const deg2rad = (degrees: number) => degrees * (Math.PI / 180)

  return (
    <>
      {model ? (
        <group
          dispose={null}
        >
          <primitive
            position={[0, 0, 0]}
            rotation={[deg2rad(0), deg2rad(72), deg2rad(0)]}
              name="Object_0"
            object={model}
          />
        </group>
      ) : (
        <Html>Loading...</Html>
      )}
    </>
  )
}
