/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    挤压: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function XIGLogo(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./xig-logo.gltf') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, -0.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.挤压.geometry}
          material={materials.Material}
          position={[-6.92, -44.37, -352.02]}
          scale={4}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./xig-logo.gltf');
